name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: root-project
            path: .
            target: esp32s3
          - name: basic-playback-example
            path: components/uac2_host/examples/basic_playback
            target: esp32s3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ${{ matrix.name }}
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4
          target: ${{ matrix.target }}
          path: ${{ matrix.path }}
